### ISSUE TITLE
Unused method?

### ISSUE THREAD

**Issue by twingly-mob** [amironoff/twingly-search-api-dotnet#10]
This method: https://github.com/amironoff/twingly-search-api-dotnet/blob/204aed7212fca2058848db58f878101ca6ad2f30/Twingly.Search.Client/Infrastructure/Extensions.cs#L57-L86 seems to be unused

**Comment by amironoff** [comment]
Great job noticing that! Removed the method.

**Comment by amironoff** [comment]
Fixed in https://github.com/amironoff/twingly-search-api-dotnet/commit/fb9879ffd6a98a12979a3ae2b84aaa227c8542b7
