### ISSUE TITLE
Be able to change SearchPattern without rebuilding query

### ISSUE THREAD

**Issue by twingly-mob** [amironoff/twingly-search-api-dotnet#11]
It's an internal setter: https://github.com/amironoff/twingly-search-api-dotnet/blob/204aed7212fca2058848db58f878101ca6ad2f30/Twingly.Search.Client/Domain/Query.cs#L25-L31

What's your reasoning behind this? We think it could be useful to be able to change it and re-run the query with the same dates etc.

**Comment by amironoff** [comment]
Valid point. I usually err on the side of object immutability. This helps enforce valid object state at all times. False alarm in this case, i'll make it public.
