### ISSUE TITLE
Use same fixtures as the other clients

### ISSUE THREAD

**Issue by twingly-mob** [amironoff/twingly-search-api-dotnet#12]
All of our clients use the same fixtures for the tests: https://github.com/twingly/twingly-search-api-ruby/tree/4d053df7bf9e477e964cb01dcea174bfd156be02/spec/fixtures

Would be good if the same fixtures were used in the tests here too.

**Comment by amironoff** [comment]
I'm afraid this is out of the originally negotiated scope :( I'm happy to discuss this as an add-on, separately funded change, should you feel this is highly needed. Nice idea though.

**Comment by twingly-mob** [comment]
Okay, let's focus on the coverage instead.

* `minimal_valid_result.xml` covered by `SuccessfulApiResponse.5posts.xml` (and #16)
* `non_xml_result.xml` covered by `UnknownFormatResponse.xml`
* `nonexistent_api_key_result.xml` covered by `ApiKeyDoesNotExistResponse.xml`
* `service_unavailable_result.xml`  covered by `ServiceUnavailableResponse.xml`
* `unauthorized_api_key_result.xml` covered by `UnauthorizedApiKeyResponse.xml`
* `undefined_error_result.xml` not covered, see comment below
* `valid_non_blog_result.xml` not covered, see #17
* `valid_result.xml` not covered, this is a large fixture, and the point of it is to catch [slow a parser](https://github.com/twingly/twingly-search-api-node/issues/10), we can add this ourselves if you still feel it's out of scope

Could you take care of `undefined_error_result.xml` as you covered all the other errors that [the server can return](https://github.com/twingly/twingly-search-api-ruby/commit/1bf9b581a8f848c805dabdbb7892b99c5e7772af)?

**Comment by amironoff** [comment]
I added a new When_ReceivedAnUnknownErrorResult_ShouldThrow() that verifies that a TwinglyRequestException is thrown in case of undefined_error_result.xml
