### ISSUE TITLE
What is the verbose tracer used for?

### ISSUE THREAD

**Issue by twingly-mob** [amironoff/twingly-search-api-dotnet#13]
We found it in https://github.com/amironoff/twingly-search-api-dotnet/blob/28b14c9081a364cac6a51b3f7d672215f803443b/Twingly.Search.Client/TwinglySearchClient.cs#L25 and it seems to be used for some sort of logging. Is it intentionally left in?

**Comment by amironoff** [comment]
Yes. It's used for performance profiling and doesn't cause any performance penalties worth consideration. I'll shut it off completely, but will keep the tracer in place.

**Comment by twingly-mob** [comment]
How do you use it? Can't the tracer level be configured via the config file rather then requiring a change in the code (it was changed from `Verbose` to `Off`)? We skimmed through https://msdn.microsoft.com/en-us/library/system.diagnostics.tracesource(v=vs.110).aspx so our level of knowledge is very basic.

**Comment by amironoff** [comment]
Sure it can be configured via the config file. On the other hand, why should it? :) This is meant purely for library developers, not for the client. 

I replaced this with the Debug tracing. It's enabled only in Debug builds and can be seen in Visual Studio Output window.

![image](https://cloud.githubusercontent.com/assets/10373681/14916528/c97d8bc4-0e22-11e6-8b55-e6b180810bf6.png)
