### ISSUE TITLE
What's the source of the NuGet scripts?

### ISSUE THREAD

**Issue by twingly-mob** [amironoff/twingly-search-api-dotnet#15]
The scripts here:

https://github.com/amironoff/twingly-search-api-dotnet/tree/204aed7212fca2058848db58f878101ca6ad2f30/Twingly.Search.Client/_CreateNewNuGetPackage

If we need to make changes, e.g. some new version of NuGet breaks things, where do we look for help/updated versions? Is it possible to use external tools for this instead of the need of having the files in the repository? We are thinking of the long-term maintainability.

Follow-up question: does the `NuGet.exe` binary need to be part of the repository? We think it's reasonable to require that NuGet is globally installed to avoid the binary in the repository.

**Comment by amironoff** [comment]
That's a set of handy Powershell scripts by Daniel Schroeder. Here's the link to the project page - https://newnugetpackage.codeplex.com/wikipage?title=NuGet%20Package%20To%20Create%20A%20NuGet%20Package%20From%20Your%20Project%20After%20Every%20Build&referringTitle=Home It's on Nuget too - https://www.nuget.org/packages/CreateNewNuGetPackageFromProjectAfterEachBuild/

In case new version of NuGet breaks things, you'll have to update/rewrite the scripts, regardless of whether you write them yourself or use an off-the-shelve package. I haven't heard about any enterprise-level solutions for package generation, that work magically no matter what.

Regarding Nuget.exe, I believe keeping it in the source is most convenient for you. That's for two reasons:

- You don't have to install nuget and add it to PATH on each machine. That's one setup checklist item less!
- You're safe from Nuget.exe signature changes - it'll stay compatible with the build scripts. That way, you're free to decide when to upgrade to newer Nuget versions (and whether you should do it at all).

**Comment by amironoff** [comment]
Guess i'll add a few sentences about this package generation routine to README, so that you remember how/why your Nuget package is created.

**Comment by twingly-mob** [comment]
Thanks for providing the source and additional information, README update sounds great!

We think we will re-arrange things on our own later.

**Comment by amironoff** [comment]
I updated the readme with info about publishing to NuGet/package generation.
