### ISSUE TITLE
Tests: Explicitly check attribute values

### ISSUE THREAD

**Issue by twingly-mob** [amironoff/twingly-search-api-dotnet#16]
We are thinking of these checks: https://github.com/amironoff/twingly-search-api-dotnet/blob/e135ffb7c730753981921d86296fb908d8b2e6d6/Twingly.Search.Tests/TwinglySearchClientTests.cs#L116-L120

Just checking for non-empty strings is not safe enough. We had [related issues in the past](https://github.com/twingly/twingly-search-api-php/issues/17), that's why we want to see explicit tests.

Here is what we mean: https://github.com/twingly/twingly-search-api-java/blob/73b64d64418dda117e922f49e957ea0877aec9f6/src/test/groovy/com/twingly/search/client/UrlConnectionClientSpockTest.groovy#L177-L230

**Comment by twingly-mob** [comment]
We would recommend using the [minimal_valid_result.xml](https://github.com/twingly/twingly-search-api-java/blob/73b64d64418dda117e922f49e957ea0877aec9f6/src/test/resources/com/twingly/search/client/minimal_valid_result.xml) fixture, as it has been hand-crafted to cover gotcha cases.

**Comment by amironoff** [comment]
minimal_valid_result.xml seems incorrect. The value of 'numberOfMatchesReturned' is 1, while the xml file contains 2 results. I'll fix that in my own version.

**Comment by amironoff** [comment]
same goes for `numberOfMatchesTotal`

**Comment by amironoff** [comment]
I amended `When_ResponseIsSuccessful_Then_ShouldDeserialize` to use `minimal_valid_result.xml` and check that actual values match.

**Comment by walro** [comment]
> minimal_valid_result.xml seems incorrect. The value of numberOfMatchesReturned is 1, while the xml file contains 3 results. I'll fix that in my own version.

Oops, nice catch. Thanks!
