### ISSUE TITLE
"Press any key to continue..."

### ISSUE THREAD

**Issue by dentarg** [amironoff/twingly-search-api-dotnet#18]
The example `.exe` says "Press any key to continue..." when it has run the examples, but I can only get it to exit when I press the Enter key. Might want to change that text so it's less confusing?

**Comment by dentarg** [comment]
Or perhaps it's meant to be `ReadKey()` and not `Read()` :) (credit goes out to @walro here, I'm no C# expert)

**Comment by amironoff** [comment]
Hi @dentarg! Thanks for the feedback. This is a standard message, well-known by .NET devs and unlikely to confuse them. Since this behavior doesn't affect the client's correctness, security, performance or maintainability, I'm going to close this for now.

**Comment by walro** [comment]
I think it should be either `ReadKey()` over `Read()` to make the text correct. Or change the text to "Press enter to continue". It's simple enough for us to fix, so you may leave it.

Just for reference: [MSDN Hello World example](https://msdn.microsoft.com/en-us/library/k1sx6ed2.aspx?f=255&MSPPError=-2147217396)
