### ISSUE TITLE
Example which traverses the index

### ISSUE THREAD

**Issue by twingly-mob** [amironoff/twingly-search-api-dotnet#4]
We need an example that shows the end-user how to traverse the index (very useful for new customers).

You can take a look at the Java example as it is the closest to C#: 
https://github.com/twingly/twingly-search-api-java/blob/c5a813f687749f6bf11189172e7bf4404ff34f86/example/src/main/java/SearchPostsStream.java
or if you want a non-recursive alternative: https://github.com/twingly/twingly-search-api-python/blob/c0609a3a5d0e7df2e15a2a86e4fa53938d36fbfe/examples/find_all_posts_mentioning_github.py

Would be great if the examples could use the same search pattern to make it easier to cross-compare the result.

**Comment by amironoff** [comment]
There's an apparent bug in [areAllResultsReturned](https://github.com/twingly/twingly-search-api-java/blob/c5a813f687749f6bf11189172e7bf4404ff34f86/src/main/java/com/twingly/search/domain/Result.java)

This may mislead users into thinking that `numberOfMatchesReturned` reflects the total number of matches returned so far, over all pages. The only explanation for why this works (that I can think of) is that this expression evaluates to true, when `numberOfMatchesTotal==numberOfMatchesReturned==0 `A better way would be to just check for zero.

**Comment by amironoff** [comment]
Added an example. I wonder if the Java example actually doesn't go into an infinite loop. The starting point for each batch should be _a little bit_ into the future. Otherwise, we might get stuck at the last item in the result ser forever..

**Comment by twingly-mob** [comment]
We believe that the Java implementation works as it implements the pagination according to https://developer.twingly.com/resources/search/#pagination

What we do is: we keep issuing requests to the API, shrinking the time window each time (by sorting on oldest first (by published time) and moving the `ts` parameter) until the query will return less results than your specified `page-size` (default 1000), i.e. `numberOfMatchesReturned == numberOfMatchesTotal`. You know then that you are done. So there is no need to do requests until you get `numberOfMatchesReturned=0`.

Also, you should use `matchingDocs.Posts.Last().Published.Value` without adding time to it, because if you do add time, there is a possibility that you will miss documents that are published at the same second as the last document. Given a small enough `page-size`, you may, as you noted, get stuck, but in general we don't get more than 1000 documents at the same second, if you have a reasonable `searchpattern`.

**Comment by twingly-mob** [comment]
We have an open issue to make this even more clear in our developer documentation.

**Comment by amironoff** [comment]
Well, if i didn't add that second, this specific example did get stuck. Would you like your customers to run an example that goes into an infinite loop? :)

**Comment by walro** [comment]
I think we missed this one when doing the final review :)

> Well, if i didn't add that second, this specific example did get stuck. Would you like your customers to run an example that goes into an infinite loop? :)

https://github.com/amironoff/twingly-search-api-dotnet/blob/d69bf50c9f1ed60f317573e4fa32150a087f4817/Twingly.Search.Client/Domain/QueryResult.cs#L46 this line needs to be removed, I think it's why you got stuck. There's no need to keep adding time until you get 0 results back, when your last query's results are equal to the total number of results, then you know you are done. As we mentioned above, the only time you may get stuck (what we know of at least) is when you get more than your `page-size` back on the same second and that is extremtly rare unless you search for, say, ` ` or fiddle with the `page-size`.

**Comment by walro** [comment]
I might add that adding a second will make you miss out on results. Say you get 1001 hits, using a a page-size of 1000. 1000 and 1001 have the same published time, adding a second and re-running the query will make you miss that 1001th result.

**Comment by amironoff** [comment]
Thanks for clearing this up. I pushed a fix in b4d7f6e

**Comment by walro** [comment]
👍
