### ISSUE TITLE
Set user-agent in the examples

### ISSUE THREAD

**Issue by twingly-mob** [amironoff/twingly-search-api-dotnet#5]
… to show the end-user that it is possible and how it's done.

**Comment by twingly-mob** [comment]
Would be great in the README too

**Comment by amironoff** [comment]
The user-agent as it is now is useful for your analysts - that way they can say which client versions are still in use and which can be dropped from support. 

What're the benefits for letting client user set a different user-agent anyway?

**Comment by twingly-mob** [comment]
Great point about the traceability, this is something we should think about in all clients.

The reason to why we want to show the end-users how to set the agent is that we [recommend](https://developer.twingly.com/resources/search/#best-practices) them to identify theirselves via the user agent.

**Comment by amironoff** [comment]
Okay, i'll implement user-agents in form [User-modifiable user agent string]/.NET Client [assembly version]. That way you'll have the best of two worlds. Will you be happy with that?

**Comment by walro** [comment]
That is perfect! 👍
