### ISSUE TITLE
About the search pattern query parameter

### ISSUE THREAD

**Issue by twingly-mob** [amironoff/twingly-search-api-dotnet#7]
Pretty sure the API doesn't make a difference right now, but according to our documentation, the string should be all lowercase: `searchpattern` and not `searchPattern` as seen in the code right now:

https://github.com/amironoff/twingly-search-api-dotnet/blob/204aed7212fca2058848db58f878101ca6ad2f30/Twingly.Search.Client/TwinglySearchClient.cs#L26

It's the same thing in the Constants class: https://github.com/amironoff/twingly-search-api-dotnet/blob/204aed7212fca2058848db58f878101ca6ad2f30/Twingly.Search.Client/Domain/Constants.cs#L15

Also, we think the constant should be used in the client class, but not in the tests.

**Comment by amironoff** [comment]
Re "we think the constant should be used in the client class, but not in the tests.": why do you think so?

**Comment by dentarg** [comment]
> Re "we think the constant should be used in the client class, but not in the tests.": why do you think so?

Why define a constant only to be used in a test? That seems backwards to me. In my mind, you define a constant because you want to use it in the implementation. Sure, I can accept that the tests define their own constants to use, but now the constant that is only used in the tests are mixed with the constants used in the implementation. 

If the constant was used in the implementation, we suggest not using it in the test, because `Constants.SearchPattern == Constants.SearchPattern` wouldn't be a great test. :)

Does any of this make sense?

**Comment by amironoff** [comment]
Hey @dentarg, this sure makes sense! What if we look at the issue from a different perspective:

1. The test treats TwinglySearchClient as a black box. It doesn't know/doesn't care how the search pattern name is set in the HTTP request, but expects it to be defined by the domain. You wouldn't want to separately define request parameter names in domain and test libs - that leads to errors.

2. The line you're referring to doesn't test whether _ 'Constants.SearchPattern == Constants.SearchPattern' _it checks that the _Query_ domain object was properly serialized to _HTTP request query string_. I.e. it compares whether _HttpRequest.QueryString["searchpattern"] == "A valid query"_

3. I think it actually would be better if TwinglySearchClient referred to the Constants.SearchPattern too. So i'll fix that. Constant usage in test should stay 'as-is' though.

Does that clarify things?

**Comment by twingly-mob** [comment]
> I think it actually would be better if TwinglySearchClient referred to the Constants.SearchPattern too. So i'll fix that.

Yeah, this was our main "concern", please go ahead and make this change.

> Does that clarify things?

We think we understand your point, we can leave it as it is now.
